name: Build and Publish

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test service
      run: |
        make test
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Increment version
      id: version   
      uses: vinodhraj/Bump-N-Tag-Version@master
      with:
        file_name: './VERSION'
        tag_version: "true"
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
    - name: push service
      run: |
        make push
    - name: update civo deployment
      uses: kvrhdn/tfe-run@v1
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        workspace: civocloud-iac-k8s-https-webservice
        message: |
          Run triggered using civocloud-iac-k8s-https-webservice (commit: ${{ github.SHA }})
        wait-for-completion: true
        type: plan
      id: civocloud-iac-k8s-https-webservice 
    - name: civo ip address
      run : echo ${{ steps.civocloud-iac-k8s-https-webservice.outputs.public_ip_addr }}
