name: Build, publish Docker and deploy to CIVO

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test service
      run: |
        make test
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Increment version
      id: version   
      uses: vinodhraj/Bump-N-Tag-Version@master
      with:
        file_name: './VERSION'
        tag_version: "true"
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
    - name: push service
      run: |
        make push
    - name: update civo deployment
      uses: kvrhdn/tfe-run@v1
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        organization: Test-maddocks
        workspace: golang-webservice
        message: |
          Terrform Cloud Run triggered (commit: ${{ github.SHA }})
        directory: terraform/
        wait-for-completion: true
        type: apply
      id: golang-webservice
