name: Build and Push

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test service
      run: |
        make test
    - name: build container
      run: |
        make container
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}   
        password: ${{ secrets.DOCKER_PASSWORD }}  
    - name: build service, container and push to dockerhub
      run: |
        make push
